### ISSUE TITLE
Intaller fails on step create-mobile-client-crd : Copy CRD definition to tmp file

### ISSUE THREAD

**Issue by mmusil** [aerogear/mobile-core#140] opened 2018-07-12 09:51 UTC
## Description
**WHAT**: Unable to install with error in the ansible script
**WHERE**: Fedora 28
**WHEN**: The SO did not have installed the `libselinux-python`

<img width="1188" alt="screen shot 2018-08-15 at 16 06 39" src="https://user-images.githubusercontent.com/7708031/44173434-ccd93580-a0d7-11e8-8672-481c3b1df0a7.png">

### Following the workaround.
* Run `$yum install libselinux-python` then try to install again. 
 
## Environment
* Fedora 28 ( Checked by @matskiv in the Fedora 27 too )
* Docker:  18.03.1-ce
* Python 2.7.15

```
[root@ibm-p8-kvm-03-guest-02 mobile-core]# oc version
oc v3.9.0+191fece
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO
```

## Proposed solution
* Add it to prerequisites in docs. ( by @mmusil )
* Add a check in order to see if it is or not installed OR add role to install it automatically  when the installation is performed in the FEDORA (by @camilamacedo86)

**Comment by matskiv** [comment] 2018-07-12 10:30
Fedora 27 as well.
I installed it like this:
`sudo dnf install libselinux-python`

**Comment by camilamacedo86** [comment] 2018-07-14 18:00
Hi @matskiv 

Following some points. 

* The need of this lib is in the requirements. See [here](https://github.com/aerogear/mobile-core/blob/c2e2d7d2bad769c5ba0674aea4ae08bfbad004d8/docs/walkthroughs/local-setup.adoc#tooling-requirements-required).

* Also, if you check [here](https://www.reddit.com/r/Fedora/comments/8ehrba/fedora_server_edition_with_ansible/) it can occur when the bash used in older for example from python 2 instead of Python 3.  In the PR 
https://github.com/aerogear/mobile-core/pull/181 merged we replaced `#!/bin/bash` for `#!/usr/bin/env bash` which means that now the script will use the bash from the env definitions which indeed could solve this issue faced in your case.

* It is important to highlight, that if we check the ansible tasks which will install few requirements it is fixed for the platforms 25 and 26 which indeed could be a reason for the issue tracked here too since the downloads and installations which are running for the versions 25 and 26 which could have this lib will not occur. See [here](https://github.com/aerogear/mobile-core/search?q=Fedora&unscoped_q=Fedora) @jasonmadigan @maleck13 is it not an issue? Should we not run the ansible script for ALL Fedora platforms?

**Comment by matskiv** [comment] 2018-07-16 07:57
@camilamacedo86 I was following docs on aerogear website: https://docs.aerogear.org/aerogear/latest/getting-started.html and this lib was not mentioned in prerequisites there. So perhaps this should be an issue for aerogear/mobile-docs ?

**Comment by mmusil** [comment] 2018-07-17 13:09
@camilamacedo86 @matskiv I think it would even make sense to add some check to the installer itself and if necessary, install it or just put step that would try to install it either way. With Ansible it should be easy thing to do :)

**Comment by camilamacedo86** [comment] 2018-07-17 13:52
@mmusil 

My point is that the issue faced/described will not so long occur probably. Because of the change performed in the #181. (Please, check my comment above) However, the ansible scripts are covering just the versions 25 and 26 of Firefox which I believe that is wrong and should cover all platforms. In this way, it will be covered by the installation already and is not so long required the check. 

@maleck13 why the ansible scripts are with these versions fixed [here|https://github.com/aerogear/mobile-core/blob/07448eeda9d1e02931254d06c64914e185414ba8/installer/roles/oc-cluster-up/meta/main.yml#L19] for example instead of ALL? Should it not cover all versions?

**Comment by matskiv** [comment] 2018-07-17 14:07
@camilamacedo86  So you think that libselinux-python is installed for one of the python version by default? And that's why it will work with bash from env?

**Comment by camilamacedo86** [comment] 2018-07-23 21:00
@matskiv I think that 2 things could cause/solve this issue. 
One is the version of the bash used as you described that indeed could already have it installed and another point here is that some roles were not been executed for the newer Fedora versions. Please, could you check the PR https://github.com/aerogear/mobile-core/pull/193/files? Please, let us know if it solved your issue. 

c/c @mmusil

**Comment by pmacko1** [comment] 2018-07-30 12:38
hi @camilamacedo86 im running a fedora 28 in vm and encountered this error as well. I installed `python-dnf` and `libeselinux-python`. This should be in docs.aerogear.org.

**Comment by camilamacedo86** [comment] 2018-07-30 12:40
@pmacko1 the  PR which is not merged yet https://github.com/aerogear/mobile-core/pull/193 should solve this scenario.

**Comment by camilamacedo86** [comment] 2018-08-15 21:06
I could reproduce this error with a VM and the version Fedora 28 today. 
Then, we need to see how to install it automatically and/or check if it installed when the SO is Fedora. 

<img width="1188" alt="screen shot 2018-08-15 at 16 06 39" src="https://user-images.githubusercontent.com/7708031/44173286-648a5400-a0d7-11e8-891b-9cb2f41eb880.png">

@pmacko1 I will update the description here to make the issue clear.

**Comment by wei-lee** [comment] 2018-12-07 10:07
Hi @mmusil,

Thanks for your feedback. This repo is now deprecated and is replaced by [Mobile Developer Console](https://github.com/aerogear/mobile-developer-console). Could you please give it a try and if you still experience the same problem, please open a new issue in that project.

Thanks.

**Closed by wei-lee** 2018-12-07 10:07 UTC
Labels: bug, component/installer
